spring.application.name=OnlineBankingSystem
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=root
spring.datasource.password=Ar@291103
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
